layout_spectrum: 0.2638298
name: OLIBLOCK
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 1
  lightness: 0.1428343
  saturation: 0.818688
  rhythmicContrast: 0.5988714
  brandColors:
    - '#C7B491'
    - '#1F1E1E'
    - '#BCFCFF'
    - '#425477'
    - '#6EACE0'
typography_spectrum: 1
