name: OLIBLOCK
favicon: null
layout_spectrum: 0.07659575
typography_spectrum: 0.58876
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#007e9e'
    - '#00465f'
    - '#89c8c3'
    - '#f7f4d6'
    - '#51abb0'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
