layout_spectrum: 0
name: OLIBLOCK
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 1
color:
  brandStrength: 1
  lightness: 0.3340425
  saturation: 0.1723404
  rhythmicContrast: 0.6765957
  brandColors:
    - '#CEBB9A'
    - '#540054'
    - '#5C6D7F'
    - '#C83A5B'
    - '#7F7803'
