layout_spectrum: 0.07659575
name: OLIBLOCK
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 1
  lightness: 0.3234043
  saturation: 0.1468085
  rhythmicContrast: 0.9680851
  brandColors:
    - '#FF017F'
    - '#DD70A1'
    - '#997A8C'
    - '#FB0FC1'
    - '#FFA6C9'
typography_spectrum: 0.6021277
